### ISSUE TITLE
Failing with SSH service didn't started after 60s.

### ISSUE THREAD

**Issue by sivaprasadreddy** [leszko/jenkins-docker-slave#1]
If I use **leszko/jenkins-docker-slave** docker image that is already published on DockerHub it is working fine. But, if I clone this repo and try to build the image and use it to create a docker based dynamic agent it is failing with the following error:

```
SEVERE: Error in provisioning; template='DockerTemplate{configVersion=2, labelString='', connector=io.jenkins.docker.connector.DockerComputerSSHConnector@20572036, remoteFs='/home/jenkins/jenkins_home', instanceCap=100, mode=NORMAL, retentionStrategy=com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy@33da7714, dockerTemplateBase=DockerTemplateBase{image='sivaprasadreddy/jenkins-docker-slave', pullCredentialsId='', registry=DockerRegistryEndpoint[null;credentialsId=null], dockerCommand='', hostname='', dnsHosts=[], network='', volumes=[], volumesFrom2=[], environment=[], bindPorts='', bindAllPorts=false, memoryLimit=null, memorySwap=null, cpuShares=null, privileged=true, tty=false, macAddress='null', extraHosts=[]}, removeVolumes=false, pullStrategy=PULL_LATEST, nodeProperties=[], disabled=BySystem,0 ms,4 min 59 sec,Template provisioning failed.}' for cloud='docker'
java.io.IOException: SSH service didn't started after 60s.
	at io.jenkins.docker.connector.DockerComputerSSHConnector.createLauncher(DockerComputerSSHConnector.java:231)
	at io.jenkins.docker.connector.DockerComputerConnector.createLauncher(DockerComputerConnector.java:96)
	at com.nirima.jenkins.plugins.docker.DockerTemplate.doProvisionNode(DockerTemplate.java:507)
	at com.nirima.jenkins.plugins.docker.DockerTemplate.provisionNode(DockerTemplate.java:468)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.run(DockerCloud.java:351)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

The only change I made is installing **git** and **locales** in image. My cloned repo https://github.com/sivaprasadreddy/jenkins-docker-slave

Any idea why it is not working?

**Comment by leszko** [comment]
Hi @sivaprasadreddy ,

The sshd is not started. You'll probably need to start sshd inside wrapdocker like I did. Though, I don't know from the top of my head, why it was needed to be done this way.

**Comment by sivaprasadreddy** [comment]
I made few changes to make it work.

We need to install **locales** package in order to use **locale-gen** command.

In **Dockerfile**

```
RUN apt-get install -qqy \
    apt-transport-https \
    ca-certificates \
    curl \
    lxc \
    iptables \
    locales
```
Need to change `docker daemon` to `dockerd` in **wrapdocker** file.

With these changes its working fine now. Thank you.

**Comment by leszko** [comment]
Cool, happy that it works now :)
